# Generated by Django 3.2.8 on 2021-11-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='registro_de_clase',
            field=models.ManyToManyField(blank=True, to='gym.Clase'),
        ),
    ]
