# Generated by Django 3.2.8 on 2021-11-03 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_alter_persona_registro_de_clase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='registro_de_clase',
            new_name='clases',
        ),
    ]
