# Generated by Django 3.2.8 on 2021-11-06 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_rename_registro_de_clase_persona_clases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='equipos_de_entrenamiento',
            field=models.ManyToManyField(blank=True, null=True, to='gym.EquipoDeEntrenamiento'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='clases',
            field=models.ManyToManyField(blank=True, null=True, to='gym.Clase'),
        ),
    ]
